### ISSUE TITLE
Error while giving equation

### ISSUE THREAD

**Issue by Varadut1** [sabari205/Equation-solver#10]
**I am getting following after equation is uploaded and started solving, Can you please look upon it? I am also adding screen shot with it.**

........Program Initiated.......

 Resizing Image........
#---------Image Info:--------#
        Height = 720 
        Width = 1320
Noise Removal
Character Segmentation

Lines : 0

Average Width of Each Letter:-  0
2023-08-25 18:03:45.360799: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2023-08-25 18:03:45,890] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restful\_init_.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 109, in view     
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restful\_init_.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "D:\Sem 5\EDI\Equation-Solver-master\Equation-Solver\app.py", line 33, in post
    operation = main(operation)
  File "D:\Sem 5\EDI\Equation-Solver-master\Equation-Solver\main.py", line 90, in main
    equation = processor('input.png')
  File "D:\Sem 5\EDI\Equation-Solver-master\Equation-Solver\main.py", line 81, in processor
    results = model.predict(X_data)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1711, in predict
    data_handler = data_adapter.get_data_handler(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1398, in get_data_handler
    return DataHandler(*args, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1152, in _init_
    adapter_cls = select_data_adapter(x, y)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 988, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 988, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 707, in can_handle
    _is_distributed_dataset(x))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1699, in _is_distributed_dataset
    return isinstance(ds, input_lib.DistributedDatasetInterface)
AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'

![WhatsApp Image 2023-08-25 at 18 25 03](https://github.com/sabari205/Equation-Solver/assets/97576501/110ad4ad-3458-4fa4-bd4e-1e18dec6152e)
![WhatsApp Image 2023-08-25 at 18 25 03 (1)](https://github.com/sabari205/Equation-Solver/assets/97576501/e97c2441-98ef-44e7-b0ff-aefeaa79f1be)

**Comment by chongbaolong** [comment]
Hi, can you open this application and the function work successfully?

**Comment by Lakshmi-14** [comment]
This error is because of the updated versions of dependencies. 

**Temporary fix :**
Install tensorflow v2.12
`pip install --ignore-installed --upgrade tensorflow==2.12`

**Comment by surajsubramanian** [comment]
Thanks a lot for raising the issue 🤗 

Hope issue is addressed with the latest commits and it's easy to get this up and running. I believe `tensorflow.python.keras` was deprecated and I had to replace it with `tensorflow.keras` [here](https://github.com/sabari205/Equation-Solver/pull/12/files#diff-c2c3b0c64a2690193a471cfc8068fcb622a23e1b4323c693b6ba20835f26fb88L8)

Feel free to raise PRs for any improvements you'd like to make, be it formatting or even an improved model.
